/**
 * Regenerates `contract.json` — the snapshot both language sides assert against.
 *
 *   node --experimental-strip-types packages/feature-schema/contract.ts   (or: npx tsx …)
 *
 * The contract exists because doc 09's P3 exit criterion is "schema contract test TS ↔ Python
 * passes". Both sides *derive* the contract from `feature-schema.json` independently and compare
 * to this committed snapshot, so a schema edit that is applied on only one side fails a test
 * instead of silently producing columns that do not line up.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const HERE = import.meta.dirname;

interface FeatureDef {
  name: string;
  group: string;
  type: string;
}

interface Schema {
  schemaVersion: number;
  features: FeatureDef[];
  targets: { name: string }[];
}

const schema = JSON.parse(readFileSync(join(HERE, 'feature-schema.json'), 'utf8')) as Schema;

const names = schema.features.map((f) => f.name).sort();
const countsByGroup: Record<string, number> = {};
for (const f of schema.features) countsByGroup[f.group] = (countsByGroup[f.group] ?? 0) + 1;

/**
 * Digest over name+group+type of every feature, sorted. Any rename, retype or regrouping changes
 * it — including one that keeps the feature count the same, which a count alone would miss.
 */
const digest = createHash('sha256')
  .update(
    JSON.stringify(
      schema.features.map((f) => [f.name, f.group, f.type]).sort((a, b) => String(a[0]).localeCompare(String(b[0]))),
    ),
  )
  .digest('hex');

const contract = {
  $comment: 'Generated by packages/feature-schema/contract.ts — do not edit by hand. Regenerate after any schema change.',
  schemaVersion: schema.schemaVersion,
  featureCount: schema.features.length,
  countsByGroup,
  targets: schema.targets.map((t) => t.name),
  digest,
  names,
};

writeFileSync(join(HERE, 'contract.json'), `${JSON.stringify(contract, null, 2)}\n`);
console.log(`contract.json: schemaVersion ${contract.schemaVersion}, ${contract.featureCount} features, digest ${digest.slice(0, 16)}…`);
for (const [g, n] of Object.entries(countsByGroup).sort()) console.log(`  ${g}: ${n}`);
