/** FR-02 — lockfile parsing into one dependency graph, for all four supported formats. */
import { describe, expect, it } from 'vitest';
import {
  detectLockKind,
  duplicateVersions,
  graphSummary,
  parseLockfile,
  parsePnpmKey,
  parseYarnClassicEntries,
  transitiveClosure,
  UnknownLockfileError,
} from '../src/index.ts';

/**
 * One app expressed in four lockfile formats, so the parsers can be held to the same assertions:
 *   app -> date-fns@4.1.0
 *   app -> react@18.3.1 -> loose-envify@1.4.0 -> js-tokens@4.0.0
 *   app -> vitest@3.0.5 (dev only)
 *   @scope/thing@2.0.0 -> js-tokens@3.0.2   (unreachable from the app; duplicates js-tokens)
 */
const PKG_JSON = {
  name: 'demo',
  dependencies: { 'date-fns': '^4.1.0', react: '^18.3.1' },
  devDependencies: { vitest: '^3.0.0' },
};

const NPM_V3 = JSON.stringify({
  name: 'demo',
  lockfileVersion: 3,
  packages: {
    '': {
      name: 'demo',
      dependencies: { 'date-fns': '^4.1.0', react: '^18.3.1' },
      devDependencies: { vitest: '^3.0.0' },
    },
    'node_modules/date-fns': { version: '4.1.0' },
    'node_modules/react': { version: '18.3.1', dependencies: { 'loose-envify': '^1.1.0' } },
    'node_modules/loose-envify': { version: '1.4.0', dependencies: { 'js-tokens': '^3.0.0 || ^4.0.0' } },
    'node_modules/js-tokens': { version: '4.0.0' },
    'node_modules/vitest': { version: '3.0.5', dev: true },
    'node_modules/@scope/thing': { version: '2.0.0', dependencies: { 'js-tokens': '^3.0.0' } },
    'node_modules/@scope/thing/node_modules/js-tokens': { version: '3.0.2' },
  },
});

const PNPM_V9 = [
  "lockfileVersion: '9.0'",
  '',
  'importers:',
  '  .:',
  '    dependencies:',
  '      date-fns:',
  '        specifier: ^4.1.0',
  '        version: 4.1.0',
  '      react:',
  '        specifier: ^18.3.1',
  '        version: 18.3.1',
  '    devDependencies:',
  '      vitest:',
  '        specifier: ^3.0.0',
  '        version: 3.0.5',
  '',
  'packages:',
  '  date-fns@4.1.0: {}',
  '  react@18.3.1: {}',
  '  loose-envify@1.4.0: {}',
  '  js-tokens@4.0.0: {}',
  '  js-tokens@3.0.2: {}',
  '  vitest@3.0.5: {}',
  "  '@scope/thing@2.0.0': {}",
  '',
  'snapshots:',
  '  date-fns@4.1.0: {}',
  '  react@18.3.1:',
  '    dependencies:',
  '      loose-envify: 1.4.0',
  '  loose-envify@1.4.0:',
  '    dependencies:',
  '      js-tokens: 4.0.0',
  '  js-tokens@4.0.0: {}',
  '  js-tokens@3.0.2: {}',
  '  vitest@3.0.5: {}',
  "  '@scope/thing@2.0.0':",
  '    dependencies:',
  '      js-tokens: 3.0.2',
  '',
].join('\n');

const YARN_CLASSIC = [
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
  '# yarn lockfile v1',
  '',
  '',
  '"@scope/thing@^2.0.0":',
  '  version "2.0.0"',
  '  resolved "https://registry.yarnpkg.com/@scope/thing/-/thing-2.0.0.tgz#abc"',
  '  integrity sha512-aaa==',
  '  dependencies:',
  '    js-tokens "^3.0.0"',
  '',
  'date-fns@^4.1.0:',
  '  version "4.1.0"',
  '  resolved "https://registry.yarnpkg.com/date-fns/-/date-fns-4.1.0.tgz#def"',
  '  integrity sha512-bbb==',
  '',
  'js-tokens@^3.0.0:',
  '  version "3.0.2"',
  '  resolved "https://registry.yarnpkg.com/js-tokens/-/js-tokens-3.0.2.tgz#111"',
  '  integrity sha512-ccc==',
  '',
  '"js-tokens@^3.0.0 || ^4.0.0":',
  '  version "4.0.0"',
  '  resolved "https://registry.yarnpkg.com/js-tokens/-/js-tokens-4.0.0.tgz#222"',
  '  integrity sha512-ddd==',
  '',
  'loose-envify@^1.1.0:',
  '  version "1.4.0"',
  '  resolved "https://registry.yarnpkg.com/loose-envify/-/loose-envify-1.4.0.tgz#333"',
  '  integrity sha512-eee==',
  '  dependencies:',
  '    js-tokens "^3.0.0 || ^4.0.0"',
  '',
  'react@^18.3.1:',
  '  version "18.3.1"',
  '  resolved "https://registry.yarnpkg.com/react/-/react-18.3.1.tgz#444"',
  '  integrity sha512-fff==',
  '  dependencies:',
  '    loose-envify "^1.1.0"',
  '',
  'vitest@^3.0.0:',
  '  version "3.0.5"',
  '  resolved "https://registry.yarnpkg.com/vitest/-/vitest-3.0.5.tgz#555"',
  '  integrity sha512-ggg==',
  '',
].join('\n');

const YARN_BERRY = [
  '__metadata:',
  '  version: 6',
  '  cacheKey: 8',
  '',
  '"demo@workspace:.":',
  '  version: 0.0.0-use.local',
  '  resolution: "demo@workspace:."',
  '',
  '"@scope/thing@npm:^2.0.0":',
  '  version: 2.0.0',
  '  resolution: "@scope/thing@npm:2.0.0"',
  '  dependencies:',
  '    js-tokens: "npm:^3.0.0"',
  '  languageName: node',
  '  linkType: hard',
  '',
  '"date-fns@npm:^4.1.0":',
  '  version: 4.1.0',
  '  resolution: "date-fns@npm:4.1.0"',
  '  languageName: node',
  '  linkType: hard',
  '',
  '"js-tokens@npm:^3.0.0":',
  '  version: 3.0.2',
  '  resolution: "js-tokens@npm:3.0.2"',
  '  languageName: node',
  '  linkType: hard',
  '',
  '"js-tokens@npm:^3.0.0 || ^4.0.0":',
  '  version: 4.0.0',
  '  resolution: "js-tokens@npm:4.0.0"',
  '  languageName: node',
  '  linkType: hard',
  '',
  '"loose-envify@npm:^1.1.0":',
  '  version: 1.4.0',
  '  resolution: "loose-envify@npm:1.4.0"',
  '  dependencies:',
  '    js-tokens: "npm:^3.0.0 || ^4.0.0"',
  '  languageName: node',
  '  linkType: hard',
  '',
  '"react@npm:^18.3.1":',
  '  version: 18.3.1',
  '  resolution: "react@npm:18.3.1"',
  '  dependencies:',
  '    loose-envify: "npm:^1.1.0"',
  '  languageName: node',
  '  linkType: hard',
  '',
  '"vitest@npm:^3.0.0":',
  '  version: 3.0.5',
  '  resolution: "vitest@npm:3.0.5"',
  '  languageName: node',
  '  linkType: hard',
  '',
].join('\n');

const CASES = [
  ['package-lock.json', NPM_V3, 'npm'],
  ['pnpm-lock.yaml', PNPM_V9, 'pnpm'],
  ['yarn.lock', YARN_CLASSIC, 'yarn-classic'],
  ['yarn.lock', YARN_BERRY, 'yarn-berry'],
] as const;

describe('detectLockKind', () => {
  it.each(CASES)('identifies %s as %s', (name, text, kind) => {
    expect(detectLockKind(name, text)).toBe(kind);
  });

  it('identifies an npm shrinkwrap', () => {
    expect(detectLockKind('npm-shrinkwrap.json', '{"lockfileVersion":1}')).toBe('npm');
  });

  it('sniffs content when the file name is unhelpful', () => {
    expect(detectLockKind('pasted.txt', '{"lockfileVersion": 3, "packages": {}}')).toBe('npm');
    expect(detectLockKind('pasted.txt', "lockfileVersion: '9.0'\n")).toBe('pnpm');
    expect(detectLockKind('pasted.txt', '__metadata:\n  version: 6\n')).toBe('yarn-berry');
  });

  it('returns null for something that is not a lockfile', () => {
    expect(detectLockKind('README.md', '# hello')).toBeNull();
  });
});

describe('parseLockfile — all four formats agree on the same project', () => {
  it.each(CASES)('%s finds the same runtime packages', (name, text) => {
    const g = parseLockfile(name, text, PKG_JSON);
    const runtime = g.nodes.filter((n) => !n.dev).map((n) => n.name);
    // vitest is dev-only; @scope/thing is in the lockfile but unreachable from the app's
    // dependencies, so reachability marks it (and the js-tokens@3.0.2 it pulls) dev too.
    expect(new Set(runtime)).toEqual(new Set(['date-fns', 'react', 'loose-envify', 'js-tokens']));
    expect(g.nodes.find((n) => n.name === 'vitest')?.dev).toBe(true);
    expect(g.warnings).toEqual([]);
  });

  it.each(CASES)('%s records direct vs dev dependencies', (name, text) => {
    const g = parseLockfile(name, text, PKG_JSON);
    expect([...g.direct].sort()).toEqual(['date-fns', 'react']);
    expect(g.directDev).toEqual(['vitest']);
  });

  it.each(CASES)('%s follows react -> loose-envify -> js-tokens', (name, text) => {
    const g = parseLockfile(name, text, PKG_JSON);
    expect(transitiveClosure(g, ['react'])).toEqual(new Set(['loose-envify', 'js-tokens']));
  });

  it.each(CASES)('%s detects the duplicated js-tokens versions', (name, text) => {
    const g = parseLockfile(name, text, PKG_JSON);
    expect(duplicateVersions(g)).toEqual([{ name: 'js-tokens', versions: ['3.0.2', '4.0.0'] }]);
  });

  it.each(CASES)('%s reports date-fns as present and moment as absent', (name, text) => {
    const g = parseLockfile(name, text, PKG_JSON);
    expect(g.nodes.some((n) => n.name === 'date-fns')).toBe(true);
    expect(g.nodes.some((n) => n.name === 'moment')).toBe(false);
  });
});

describe('npm specifics', () => {
  it('reads direct deps from the root entry when no package.json is given', () => {
    const g = parseLockfile('package-lock.json', NPM_V3);
    expect([...g.direct].sort()).toEqual(['date-fns', 'react']);
    expect(g.directDev).toEqual(['vitest']);
    expect(g.lockfileVersion).toBe('3');
  });

  it('parses a nested v1 tree', () => {
    const v1 = JSON.stringify({
      lockfileVersion: 1,
      dependencies: {
        react: { version: '18.3.1', requires: { 'loose-envify': '^1.1.0' } },
        'loose-envify': {
          version: '1.4.0',
          requires: { 'js-tokens': '^4.0.0' },
          dependencies: { 'js-tokens': { version: '4.0.0' } },
        },
        vitest: { version: '3.0.5', dev: true },
      },
    });
    const g = parseLockfile('package-lock.json', v1, {
      dependencies: { react: '^18' },
      devDependencies: { vitest: '^3' },
    });
    expect(g.lockfileVersion).toBe('1');
    expect(g.nodes.map((n) => `${n.name}@${n.version}`)).toEqual([
      'js-tokens@4.0.0',
      'loose-envify@1.4.0',
      'react@18.3.1',
      'vitest@3.0.5',
    ]);
    expect(transitiveClosure(g, ['react'])).toEqual(new Set(['loose-envify', 'js-tokens']));
  });

  it('skips workspace link entries', () => {
    const g = parseLockfile(
      'package-lock.json',
      JSON.stringify({
        lockfileVersion: 3,
        packages: {
          '': {},
          'node_modules/mine': { link: true, resolved: 'packages/mine' },
          'packages/mine': { version: '1.0.0' },
        },
      }),
    );
    expect(g.nodes.some((n) => n.name === 'mine')).toBe(false);
  });

  it('treats a package that is dev at one path and runtime at another as runtime', () => {
    const g = parseLockfile(
      'package-lock.json',
      JSON.stringify({
        lockfileVersion: 3,
        packages: {
          '': { dependencies: { a: '^1' } },
          'node_modules/a': { version: '1.0.0', dependencies: { shared: '^1' } },
          'node_modules/shared': { version: '1.0.0' },
          'node_modules/d/node_modules/shared': { version: '1.0.0', dev: true },
        },
      }),
    );
    expect(g.nodes.find((n) => n.name === 'shared')?.dev).toBe(false);
  });

  it('records peer dependencies', () => {
    const g = parseLockfile(
      'package-lock.json',
      JSON.stringify({
        lockfileVersion: 3,
        packages: {
          '': { dependencies: { 'react-dom': '^18' } },
          'node_modules/react-dom': { version: '18.3.1', peerDependencies: { react: '^18.3.1' } },
        },
      }),
    );
    expect(g.nodes.find((n) => n.name === 'react-dom')?.peerDeps).toEqual(['react']);
  });
});

describe('pnpm key parsing across generations', () => {
  it.each([
    ['/date-fns/4.1.0', 'date-fns', '4.1.0'],
    ['/@scope/thing/2.0.0', '@scope/thing', '2.0.0'],
    ['/date-fns@4.1.0', 'date-fns', '4.1.0'],
    ['date-fns@4.1.0', 'date-fns', '4.1.0'],
    ['@scope/thing@2.0.0', '@scope/thing', '2.0.0'],
    ['react-dom@18.3.1(react@18.3.1)', 'react-dom', '18.3.1'],
  ])('%s -> %s @ %s', (key, name, version) => {
    expect(parsePnpmKey(key)).toEqual({ name, version });
  });

  it('parses a v6 lockfile where the edges live in packages', () => {
    const v6 = [
      "lockfileVersion: '6.0'",
      '',
      'dependencies:',
      '  react:',
      '    specifier: ^18.3.1',
      '    version: 18.3.1',
      '',
      'packages:',
      '',
      '  /react@18.3.1:',
      '    resolution: {integrity: sha512-aaa==}',
      '    dependencies:',
      '      loose-envify: 1.4.0',
      '    dev: false',
      '',
      '  /loose-envify@1.4.0:',
      '    resolution: {integrity: sha512-bbb==}',
      '    dependencies:',
      '      js-tokens: 4.0.0',
      '    dev: false',
      '',
      '  /js-tokens@4.0.0:',
      '    resolution: {integrity: sha512-ccc==}',
      '    dev: false',
      '',
    ].join('\n');
    const g = parseLockfile('pnpm-lock.yaml', v6, { dependencies: { react: '^18.3.1' } });
    expect(g.lockfileVersion).toBe('6.0');
    expect(transitiveClosure(g, ['react'])).toEqual(new Set(['loose-envify', 'js-tokens']));
  });

  it('strips the peer-resolution suffix so one package is not counted twice', () => {
    const g = parseLockfile(
      'pnpm-lock.yaml',
      [
        "lockfileVersion: '9.0'",
        'packages:',
        '  react-dom@18.3.1:',
        '    peerDependencies:',
        '      react: ^18.3.1',
        'snapshots:',
        '  react-dom@18.3.1(react@18.3.1):',
        '    dependencies:',
        '      scheduler: 0.23.2',
        '  scheduler@0.23.2: {}',
      ].join('\n'),
    );
    expect(g.nodes.filter((n) => n.name === 'react-dom')).toHaveLength(1);
    expect(g.nodes.find((n) => n.name === 'react-dom')?.peerDeps).toEqual(['react']);
    expect(g.nodes.find((n) => n.name === 'react-dom')?.deps).toEqual(['scheduler']);
  });
});

describe('yarn classic line parser', () => {
  it('splits multi-descriptor entries and reads nested dependency blocks', () => {
    const { entries, warnings } = parseYarnClassicEntries(YARN_CLASSIC);
    expect(warnings).toEqual([]);
    const react = entries.find((e) => e.descriptors[0] === 'react@^18.3.1');
    expect(react?.version).toBe('18.3.1');
    expect(react?.dependencies).toEqual(['loose-envify']);
    const jsTokens4 = entries.find((e) => e.descriptors[0] === 'js-tokens@^3.0.0 || ^4.0.0');
    expect(jsTokens4?.version).toBe('4.0.0');
  });

  it('separates peerDependencies from dependencies', () => {
    const { entries } = parseYarnClassicEntries(
      [
        'react-dom@^18.0.0:',
        '  version "18.3.1"',
        '  dependencies:',
        '    scheduler "^0.23.0"',
        '  peerDependencies:',
        '    react "^18.0.0"',
        '',
      ].join('\n'),
    );
    expect(entries[0]?.dependencies).toEqual(['scheduler']);
    expect(entries[0]?.peerDependencies).toEqual(['react']);
  });

  it('ignores comments and blank lines', () => {
    const { entries, warnings } = parseYarnClassicEntries('# a comment\n\n# another\n');
    expect(entries).toEqual([]);
    expect(warnings).toEqual([]);
  });
});

describe('yarn berry specifics', () => {
  it('ignores the workspace root entry', () => {
    const g = parseLockfile('yarn.lock', YARN_BERRY, PKG_JSON);
    expect(g.nodes.some((n) => n.name === 'demo')).toBe(false);
    expect(g.lockfileVersion).toBe('6');
  });
});

describe('graphSummary', () => {
  it('counts runtime packages and duplicates, excluding dev', () => {
    const s = graphSummary(parseLockfile('package-lock.json', NPM_V3, PKG_JSON));
    expect(s.distinctRuntimePackages).toBe(4);
    expect(s.duplicatedPackages).toBe(1);
    expect(s.directRuntime).toBe(2);
    expect(s.directDev).toBe(1);
    expect(s.runtimeNodes).toBeLessThan(s.totalNodes);
  });
});

describe('errors and resilience', () => {
  it('throws a typed error naming the supported formats', () => {
    expect(() => parseLockfile('README.md', '# nope')).toThrow(UnknownLockfileError);
    expect(() => parseLockfile('README.md', '# nope')).toThrow(/npm lockfileVersion 1-3, pnpm 5\/6\/9/);
  });

  it('reports a missing version as a warning instead of throwing', () => {
    const g = parseLockfile(
      'package-lock.json',
      JSON.stringify({ lockfileVersion: 3, packages: { '': {}, 'node_modules/a': {} } }),
    );
    expect(g.nodes).toEqual([]);
    expect(g.warnings).toEqual(['npm: a at node_modules/a has no version']);
  });

  it('produces an empty graph with a warning for an empty pnpm lockfile', () => {
    const g = parseLockfile('pnpm-lock.yaml', "lockfileVersion: '9.0'\n");
    expect(g.nodes).toEqual([]);
    expect(g.warnings).toEqual(['pnpm: no packages found — empty graph']);
  });
});
