'use client';

import { useCallback, useEffect, useState } from 'react';
import { Field } from './Field.tsx';

/**
 * The CAPTCHA control (FR-65).
 *
 * The SVG and its signed answer come from `/api/captcha`; the answer never reaches the browser in
 * readable form. `refreshKey` lets the parent pull a fresh challenge after a failed submit, because
 * a used or expired token must not be retried.
 */
export function Captcha({
  value,
  onChange,
  error,
  refreshKey = 0,
  disabled,
}: {
  value: string;
  onChange: (value: string) => void;
  error?: string | undefined;
  refreshKey?: number;
  disabled?: boolean;
}) {
  const [svg, setSvg] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  const load = useCallback(async () => {
    setFailed(false);
    setSvg(null);
    try {
      const res = await fetch('/api/captcha', { cache: 'no-store' });
      const body = (await res.json()) as { ok: boolean; svg?: string };
      if (body.ok && body.svg) setSvg(body.svg);
      else setFailed(true);
    } catch {
      setFailed(true);
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load, refreshKey]);

  return (
    <div className="flex flex-col gap-2">
      <div className="flex flex-wrap items-center gap-3">
        <div
          aria-live="polite"
          className="flex h-16 w-[190px] items-center justify-center overflow-hidden rounded-lg border border-[var(--color-line)] bg-[var(--color-surface)]"
        >
          {svg ? (
            // The SVG is generated by our own server from a fixed template, never from user input.
            <span dangerouslySetInnerHTML={{ __html: svg }} />
          ) : (
            <span className="text-xs text-[var(--color-ink-faint)]">{failed ? 'Could not load' : 'Loading…'}</span>
          )}
        </div>
        <button
          type="button"
          onClick={() => void load()}
          className="dl-btn dl-btn-ghost text-sm"
          aria-label="Get a different captcha image"
        >
          New image
        </button>
      </div>
      <Field
        label="Type the characters above"
        name="captcha"
        value={value}
        onChange={(v) => onChange(v.toUpperCase())}
        error={error}
        hint="Five letters or digits. Not case sensitive."
        autoComplete="off"
        maxLength={8}
        disabled={disabled}
      />
    </div>
  );
}
